project:
  type: website
  output-dir: docs
  resources: 
    - pdf/*.pdf
  preview:
    port: 8000

website:
  google-analytics:
    tracking-id: "UA-176182247-1"
    anonymize-ip: false
  title: "Hi there!"
  site-url: https://henrykye.com
  navbar:
    foreground: "#F5F5DC"
    background: "#3D2B1F"
  search: false
  page-footer: |
    © 2022 Hyungil Kye. All rights reserved.  

format:
  html:
    theme: cosmo
    css: styles.css
    include-after-body: 
      file: javascript.html



