project:
  type: website
  output-dir: docs
  resources: 
    - static/pdf/*.pdf
    - static/js/*.js
    - CNAME

website:
  title: "Hi, there!"
  site-url: https://henrykye.com
  navbar:
    foreground: "#F5F5DC"
    background: "#112D4E"
  search: false
  page-footer: |
    Hyungil Kye. All rights reserved.

format:
  html:
    theme: cosmo
    css: static/css/styles.css
    include-in-header:
      - text: '<script src="https://code.jquery.com/jquery-3.7.0.js"></script>'
      - text: '<script src="static/js/jscode.js"></script>'
      - file: google-analytics.html



